export enum CompetitionFormat {
  SINGLE_MATCH = 'SINGLE_MATCH',
  ROUND_ROBIN = 'ROUND_ROBIN',
  GROUP_STAGE = 'GROUP_STAGE',
  KNOCKOUT = 'KNOCKOUT',
  GROUP_STAGE_KNOCKOUT = 'GROUP_STAGE_KNOCKOUT',
  LEAGUE = 'LEAGUE',
  TWO_LEGGED_TIE = 'TWO_LEGGED_TIE',
}
